### ISSUE TITLE
Issue a release with a JAR

### ISSUE THREAD

**Issue by yanatan16** [shikhar/kafka-connect-dynamodb#1]
Could you please precompile a JAR for ease of installation and put it in a release?

Thanks!

**Comment by shikhar** [comment]
@yanatan16 here you go! https://github.com/shikhar/kafka-connect-dynamodb/releases/tag/0.1.0

Thanks for asking, I was just being lazy :-) 

Out of curiosity are you planning on using the source or the sink?

**Comment by szwed** [comment]
We are using both, please look into the other issues :)

**Comment by shikhar** [comment]
@szwed good to know. You seem to be the first user so I appreciate your reporting the issues you are running into! We'll figure them out :-)

**Comment by shikhar** [comment]
@szwed would you be able to give https://github.com/shikhar/kafka-connect-dynamodb/releases/tag/0.2.0 a shot?
