### ISSUE TITLE
How to handle invalid messages

### ISSUE THREAD

**Issue by maksym3d** [shikhar/kafka-connect-dynamodb#11]
Hi Shikhar,

not an issue per se, but what's a proper way of handling exceptions in the connector? Specifically, if a an invalid message gets inserted into a message queue - say a JSON with single quotes or JSON without a proper Dynamo key, - connect-dynamodb crashes and does not recover unless I delete and re-create the topic and restart the connector. Is there a better way?

thanks,
Maskym

**Comment by shikhar** [comment]
Yeah @petrenkomaxim, this could do with a good solution. It makes the most sense to handle this at the level of the Connect framework (you should open a JIRA if you'd like to start a discussion about what form that could take). See e.g. https://groups.google.com/d/msg/confluent-platform/yhcaOhFg0l8/xrIj0L5lAwAJ

cc @ewencp @gwenshap

**Comment by maksym3d** [comment]
I see, thanks for the link!
