### ISSUE TITLE
Logs meaning: com.amazonaws.dynamodb.v20120810.WriteRequest@ab00e9c3

### ISSUE THREAD

**Issue by szwed** [shikhar/kafka-connect-dynamodb#2]
Hi, 

Could you elaborate a little bit what the below logs mean?

```
com.amazonaws.dynamodb.v20120810.WriteRequest@ab00e9c3, com.amazonaws.dynamodb.v20120810.WriteRequest@ab00e9d1, com.amazonaws.dynamodb.v20120810.WriteRequest@ab00e96a, 
```

Thanks,

**Comment by szwed** [comment]
By the way, I have a feeling that the logs are too verbose (20 MB in 1 minute?) and that the new line is missing for each entry or at least in my case all of them are represented as one line.

**Comment by shikhar** [comment]
Hmm I can't identify any such logging in the connector code. I suspect these logs originate from the AWS SDK...

**Comment by szwed** [comment]
Since all the other bugs were fixed it doesn't pop up anymore. I think we can close the ticket.
