### ISSUE TITLE
kafka-connect-dynamodb causing connect cluster to become weirdly unresponsive

### ISSUE THREAD

**Issue by dollschasingmen** [shikhar/kafka-connect-dynamodb#6]
Hi,

I registered a dynamodb connect on my cluster and now the cluster has become strangely unresponsive to any REST API endpoints (for example `curl -X GET -i http://my-avro-kafka-connect.domain.com/connectors` returns a 504 Gateway Time-out error).

`curl -X GET -i http://my-avro-kafka-connect.domain.com` however, work, ie, it does return a 200.

I see nothing in the logs, no exceptions.

Additionally, the connect doesn't work (ie, doesn't seem to be writing any data to dynamodb)

I am using the sink connector with configs like this:

```
name=my-dynamodb-sink
topics=my-topic
connector.class=dynamok.sink.DynamoDbSinkConnector
region=us-east-1
ignore.record.key=true
table.format=my_table_name
```

Also, FWIW, I built off the head of master and deployed by JAR-ing the contents in `target/kafka-connect-dynamodb-0.3.0-SNAPSHOT-package/share/java/kafka-connect-dynamodb` and then adding that to the `CLASSPATH` env variable.

Any ideas on how to debug this further? Thank you.

**Comment by shikhar** [comment]
Could you get a thread dump of the Connect process? `$JAVA_HOME/bin/jstack <pid>` should do it.

I'll also try it out later today to see if I can reproduce.

**Comment by dollschasingmen** [comment]
also - more context. the topic holds avro data.

**Comment by shikhar** [comment]
@dollschasingmen What version of Kafka Connect are you using?

**Comment by dollschasingmen** [comment]
`"version":"0.10.0.0-cp1","commit":"7aeb2e89dbc741f6"`

**Comment by dollschasingmen** [comment]
hmm -- so I cleared out my `connect-configs` topic redeployed the cluster. Now `/connectors` works (although, returns blank). But `/connector-plugins` is returning a 504. Which suggests to me that perhaps there is something wrong with how I included this plugin?

I wonder if I made a mistake in the way I included this connect? I literally did a `jar cf` on `target/kafka-connect-dynamodb-0.3.0-SNAPSHOT-package/share/java/kafka-connect-dynamodb` which seems similar to how you made your zip releases. 

Should I have done something else?

**Comment by dollschasingmen** [comment]
```
jar tf kafka-connect-dynamodb-0.3.0.jar

META-INF/
META-INF/MANIFEST.MF
aws-java-sdk-core-1.11.39.jar
aws-java-sdk-dynamodb-1.11.39.jar
aws-java-sdk-kms-1.11.39.jar
aws-java-sdk-s3-1.11.39.jar
commons-codec-1.9.jar
commons-logging-1.1.3.jar
httpclient-4.5.2.jar
httpcore-4.4.4.jar
ion-java-1.0.0.jar
jackson-annotations-2.6.0.jar
jackson-core-2.6.6.jar
jackson-databind-2.6.6.jar
jackson-dataformat-cbor-2.6.6.jar
jmespath-java-1.0.jar
joda-time-2.8.1.jar
kafka-connect-dynamodb-0.3.0-SNAPSHOT.jar
```

**Comment by shikhar** [comment]
An archive containing nested JARs like that would not make the embedded JARs available as far as I know. It might make sense to include the appropriate Maven plugin so it's easy to create a valid fat JAR.

`CLASSPATH=$CLASSPATH:"$dir_containing_jars/*"` normally works, can you try with that?

**Comment by shikhar** [comment]
I would also recommend an update to the latest release CP 3.1.1 (which includes Kafka Connect 0.10.1), if possible for you. However, it should work with CP 3.0.x / 0.10.0 that you are running with.

**Comment by dollschasingmen** [comment]
i think that was it. i solved this problem with by making a fatjar using the maven shade plugin. i can make a PR to add that into the POM if you are willing to merge?

its just this:

```
+
+            <!-- Maven Shade Plugin -->
+            <plugin>
+              <groupId>org.apache.maven.plugins</groupId>
+              <artifactId>maven-shade-plugin</artifactId>
+              <version>2.3</version>
+              <executions>
+                 <!-- Run shade goal on package phase -->
+                <execution>
+                  <phase>package</phase>
+                  <goals>
+                    <goal>shade</goal>
+                  </goals>
+                </execution>
+              </executions>
+            </plugin>
+
```

**Comment by shikhar** [comment]
Thanks @dollschasingmen, I would welcome such a PR.

**Comment by dollschasingmen** [comment]
https://github.com/shikhar/kafka-connect-dynamodb/pull/8
