### ISSUE TITLE
is it expected that my connect-offsets is 0?

### ISSUE THREAD

**Issue by dollschasingmen** [shikhar/kafka-connect-dynamodb#9]
Hi -- so I have two separate instances of this connect running and everything seems to be working well! But also I noticed that my connect-offsets topic has no data in it. Is that to be expected? Are the offsets being stored somewhere else?

**Comment by shikhar** [comment]
Glad to hear it's working well for you! I believe you using the sink, so this is to be expected. Since sink connectors are backed by normal Kafka consumers, the offset storage happens in the normal `__consumer_offsets` topic, rather than the Connect-managed `__connect_offsets` topic.
